name: Test Android
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      android-version:
        required: false
        default: 35
        type: number
      react-native-version:
        required: false
        default: '0.78.3'
        type: string

jobs:
  test-Android:
    name: Test Android
    runs-on: ubuntu-24.04
    env:
      target: google_apis
      arch: x86_64
    steps:
      - name: Provide more disk space
        run: |
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc /opt/cabal /opt/stack
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf "/usr/local/share/boost"
          sudo apt-get remove -y 'php.*'
          sudo docker image prune --all --force

      - uses: actions/checkout@v5

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: actions/cache/restore@v4
        with:
          path: lib
          key: temp-lib-${{ github.sha }}

      - uses: actions/cache/restore@v4
        id: yarn-cache
        with:
          path: | 
            node_modules
            example/node_modules
          key: temp-node-${{ github.sha }}

      - name: Build dependency if needed
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: | 
          yarn
          yarn prepare

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ inputs.android-version }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ inputs.android-version }}
          target: ${{ env.target }}
          arch: ${{ env.arch }}
          force-avd-creation: false
          emulator-boot-timeout: 300
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ inputs.android-version }}
          target: ${{ env.target }}
          arch: ${{ env.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          working-directory: ./example/android
          script: |
            echo "::group::Running Android app"
            yarn android
            echo "::endgroup::"
            echo "::group::Running Tests"
            ./gradlew jacocoTestReport
            echo "::endgroup::"

      - name: Prepare Jacoco report
        run: |
          mkdir reports
          mv $(find . -name 'jacocoTestReport.xml') reports/jacoco.xml

      - name: Archive Coverage report
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-coverage-report
          path: reports
