name: Test Android

on:
  workflow_call:
    inputs:
      api-level:
        required: true
        default: 29
        type: string

jobs:
  test-Android:
    runs-on: macos-13-large
    env:
      target: google_apis
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - uses: actions/cache/restore@v3
        with:
          path: lib
          key: temp-lib-${{ github.sha }}

      - uses: actions/cache/restore@v3
        id: yarn-cache
        with:
          path: |
            node_modules
            example\node_modules
          key: temp-node-${{ github.sha }}

      - name: Build dependency if needed
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ inputs.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ inputs.api-level }}
          target: ${{ env.target }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ inputs.api-level }}
          target: ${{ env.target }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          working-directory: ./example/android
          pre-emulator-launch-script: |
            sdkmanager --list
          script: |
            echo "::group::Running Android app"
            yarn android
            echo "::endgroup::"
            echo "::group::Running Gradle Build"
            ./gradlew connectedCheck
            echo "::endgroup::"
            echo "::group::Running Tests"
            ./gradlew jacocoTestReport
            echo "::endgroup::"

      - name: Prepare Jacoco report
        run: |
          mv android/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml reports/jacoco.xml

      - name: Archive Coverage report
        uses: actions/upload-artifact@v3
        with:
          name: kotlin-coverage-report
          path: reports