name: Test Android
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      android-version:
        required: true
        type: string

jobs:
  test-Android:
    name: Test Android
    runs-on: ubuntu-24.04
    env:
      target: google_apis
      arch: x86_64
    steps:
      - uses: actions/checkout@v6

      - name: Download library
        uses: actions/download-artifact@v8
        with:
          name: built-lib
          path: lib

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run tests
        working-directory: ./example/android
        run: |
          ./gradlew jacocoTestReport

      - name: Prepare Jacoco report
        run: |
          mkdir reports
          mv $(find . -name 'jacocoTestReport.xml') reports/jacoco.xml

      - name: Archive Coverage report
        uses: actions/upload-artifact@v7
        with:
          name: kotlin-coverage-report
          path: reports
          retention-days: 1
