name: Build library
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:

jobs:
  build-lib:
    name: Build Nodes
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
            example/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build library
        run: yarn install --frozen-lockfile

      - name: Make JS coverage report
        run: |
          npx jest --coverage --coverageDirectory=reports

      - name: Archive JS Coverage report
        uses: actions/upload-artifact@v4
        with:
          name: js-coverage-report
          path: reports

      - name: Build Example app
        working-directory: example
        run: yarn install

      - name: Archive library
        uses: actions/cache/save@v4
        with:
          path: lib
          key: temp-lib-${{ github.sha }}

      - name: Archive Node Modules
        uses: actions/cache/save@v4
        with:
          path: example/node_modules
          key: temp-node-${{ github.sha }}
