name: Build library
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      build-tgz:
        type: boolean
        default: true
      build-precompiled-sdk:
        type: boolean
        default: true

jobs:
  build-lib:
    name: Build Nodes
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Build library
        run: | 
          yarn install --frozen-lockfile
          yarn prepare

      - name: Make JS coverage report
        run: |
          npx jest --coverage --coverageDirectory=reports

      - name: Archive JS Coverage report
        uses: actions/upload-artifact@v7
        with:
          name: js-coverage-report
          path: reports
          retention-days: 1

      - name: Create tgz
        if: inputs.build-tgz
        run: |
          npm pack
          mv adyen-react-native-*.tgz adyen-react-native.tgz

      - name: Archive tgz
        if: inputs.build-tgz
        uses: actions/upload-artifact@v7
        with:
          name: built-tgz
          path: adyen-react-native.tgz
          retention-days: 1

      - name: Archive precompiled SDK
        if: inputs.build-precompiled-sdk
        uses: actions/upload-artifact@v7
        with:
          name: built-lib
          path: lib
          retention-days: 1
