name: Test iOS
permissions:
  contents: read
  actions: write

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      device-version:
        required: true
        type: string

jobs:
  ios_tests:
    name: Test iOS
    runs-on: macos-15
    env:
      workspace: AdyenExample.xcworkspace
      scheme: AdyenExample
      device: iPhone ${{ inputs.device-version }}
      buildFolder: ./DerivedData
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Download library
        uses: actions/download-artifact@v7
        with:
          name: built-lib
          path: lib

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - uses: actions/cache@v5
        id: pods-cache
        with:
          path: |
            example/ios/Pods
            ~/Library/Caches/CocoaPods
          key: pods-${{ hashFiles('example/ios/Podfile.lock') }}
          restore-keys: pods-

      - name: Pod install
        working-directory: example/ios
        run: |
          if [ "${{ steps.pods-cache.outputs.cache-hit }}" != "true" ]; then
            pod install --repo-update
          else
            pod install
          fi

      - name: Run tests
        working-directory: example/ios
        run: |
          xcodebuild test \
            -workspace ${{ env.workspace }} \
            -scheme ${{ env.scheme }} \
            -destination "platform=iOS Simulator,name=${{env.device}}" \
            -derivedDataPath ${{ env.buildFolder }} \
            -enableCodeCoverage YES \
            -allowProvisioningUpdates | xcpretty --utf --color && exit ${PIPESTATUS[0]}

      - name: Generate code Coverage
        working-directory: example/ios
        run: |
          mkdir ${{ github.workspace }}/reports
          ${{ github.workspace }}/scripts/xccov-to-sonarqube-generic.sh $(find . -name "*.xcresult") > ${{ github.workspace }}/reports/sonarqube-generic-coverage.xml
          sed -i '' "s#${{ github.workspace }}/example/node_modules/@adyen/react-native/##g" ${{ github.workspace }}/reports/sonarqube-generic-coverage.xml

      - name: SwiftLint
        working-directory: ios
        run: |
          brew install swiftlint
          fastlane run swiftlint output_file:"${{ github.workspace }}/reports/swiftlint.json" reporter:"json" ignore_exit_status:"true"

      - name: Archive Coverage report
        uses: actions/upload-artifact@v6
        with:
          name: swift-coverage-report
          path: reports
          retention-days: 1
