name: Test iOS

on:
  workflow_call:
    inputs:
      device-version:
        required: false
        default: 14
        type: number
      react-native-version:
        required: false
        default: '0.71.14'
        type: string

jobs:
  ios_tests:
    name: Test iOS
    runs-on: macos-latest
    env:
      workspace: AdyenExample.xcworkspace
      scheme: AdyenExample
      device: iPhone ${{ inputs.device-version }}
      buildFolder: ./DerivedData
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - uses: actions/cache/restore@v4
        with:
          path: lib
          key: temp-lib-${{ github.sha }}

      - uses: actions/cache/restore@v4
        id: yarn-cache
        with:
          path: example/node_modules
          key: temp-node-${{ github.sha }}

      - name: Build dependency if needed
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - uses: actions/cache@v4
        with:
          path: example/ios/Pods
          key: pods-${{ hashFiles('example/ios/Podfile.lock') }}
          restore-keys: pods-

      - name: Pod install
        working-directory: example/ios
        run: pod update

      - name: Archive library
        uses: actions/cache/save@v4
        with:
          path: example/ios/Pods
          key: pods-${{ hashFiles('example/ios/Podfile.lock') }}

      - name: Run tests
        working-directory: example/ios
        run: |
          xcodebuild test \
            -workspace ${{ env.workspace }} \
            -scheme ${{ env.scheme }} \
            -destination "name=iPhone 14" \
            -derivedDataPath ${{ env.buildFolder }} \
            -enableCodeCoverage YES | xcpretty --utf --color && exit ${PIPESTATUS[0]}

      - name: Generate code Coverage
        working-directory: example/ios
        run: |
          mkdir ${{ github.workspace }}/reports
          ${{ github.workspace }}/scripts/xccov-to-sonarqube-generic.sh $(find . -name "*.xcresult") > ${{ github.workspace }}/reports/sonarqube-generic-coverage.xml
          sed -i '' "s#${{ github.workspace }}/example/node_modules/@adyen/react-native/##g" ${{ github.workspace }}/reports/sonarqube-generic-coverage.xml

      - name: SwiftLint
        working-directory: ios
        run: fastlane run swiftlint output_file:"${{ github.workspace }}/reports/swiftlint.json" reporter:"json" ignore_exit_status:"true"

      - name: Archive Coverage report
        uses: actions/upload-artifact@v3
        with:
          name: swift-coverage-report
          path: reports
