name: Scan PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop
env:
  node-version: 20

jobs:
  build-lib:
    name: Build Nodes
    uses: ./.github/workflows/build_lib.yml

  test-iOS:
    name: Test iOS
    needs: [build-lib]
    uses: ./.github/workflows/ios_tests.yml

  test-Android:
    name: Test Android
    needs: [build-lib]
    uses: ./.github/workflows/android_tests.yml

  run-sonar:
    name: Collect Sonar reports
    needs: [test-iOS, test-Android]
    uses: ./.github/workflows/run_sonar.yml
    secrets: inherit

  delete-chach:
    name: Clean up
    runs-on: ubuntu-latest
    needs: [run-sonar]
    if: always()
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Delete temporary Node cache
        continue-on-error: true
        run: |
          gh cache delete temp-node-${{ github.sha }}

      - name: Delete temporary Lib cache
        continue-on-error: true
        run: |
          gh cache delete temp-lib-${{ github.sha }}
