name: Scan PR
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches:
      - develop

concurrency:
  group: pr-check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-lib:
    name: Build Nodes
    uses: ./.github/workflows/build_lib.yml
    with:
      node-version: ${{ vars.NODE_VERSION }}
      build-tgz: ${{ contains(github.event.pull_request.labels.*.name, 'run-e2e-tests') }}
      build-precompiled-sdk: true

  test-iOS:
    name: Test iOS
    needs: [build-lib]
    uses: ./.github/workflows/ios_tests.yml
    with:
      node-version: ${{ vars.NODE_VERSION }}
      device-version: ${{ vars.IOS_DEVICE_VERSION }}

  test-Android:
    name: Test Android
    needs: [build-lib]
    uses: ./.github/workflows/android_tests.yml
    with:
      node-version: ${{ vars.NODE_VERSION }}
      android-version: ${{ vars.ANDROID_VERSION }}

  run-sonar:
    name: Collect Sonar reports
    needs: [test-iOS, test-Android]
    uses: ./.github/workflows/run_sonar.yml
    secrets: inherit
    with:
      node-version: ${{ vars.NODE_VERSION }}

  e2e-react-native:
    name: E2E Test React Native
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-tests')
    needs: [build-lib]
    uses: ./.github/workflows/e2e_test.yml
    with:
      platform: 'react-native'
      version: '0.80.2'
      node-version: ${{ vars.NODE_VERSION }}
    secrets:
      ADYEN_CLIENT_KEY: ${{ secrets.ADYEN_CLIENT_KEY }}
      ADYEN_PUBLIC_KEY: ${{ secrets.ADYEN_PUBLIC_KEY }}

  e2e-expo:
    name: E2E Test Expo
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-tests')
    needs: [build-lib]
    uses: ./.github/workflows/e2e_test.yml
    with:
      platform: 'expo'
      version: '52'
      node-version: ${{ vars.NODE_VERSION }}
    secrets:
      ADYEN_CLIENT_KEY: ${{ secrets.ADYEN_CLIENT_KEY }}
      ADYEN_PUBLIC_KEY: ${{ secrets.ADYEN_PUBLIC_KEY }}
