name: Scan PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  node-version: 16

jobs:
  build-lib:
    name: Build Nodes
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
            example/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build dependency
        run: yarn install --frozen-lockfile

      - name: Build Example app
        run: |
          cd example
          yarn install

      - uses: actions/cache/save@v3
        with:
          path: |
            lib
            node_modules
            example/node_modules
          key: temp-${{ github.sha }}

  test-iOS:
    name: Test iOS
    runs-on: macos-13-xl
    needs: [build-lib]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: |
            lib
            node_modules
            example\node_modules
          key: temp-${{ github.sha }}

      - name: Build dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - uses: actions/cache@v3
        with:
          path: example/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('example/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Pod install
        run: |
          cd example/ios
          pod install

      - name: Build and test iOS
        run: |
          cd example/ios
          xcodebuild test -workspace "${workspace}" -scheme "${scheme}" ${params} -destination "${destination}" | xcpretty --utf --color && exit ${PIPESTATUS[0]}
        env:
          workspace: 'AdyenExample.xcworkspace'
          params: '-derivedDataPath ./DerivedData -enableCodeCoverage YES'
          scheme: 'AdyenExample'
          destination: 'name=iPhone 14'

  test-Android:
    name: Test Android
    needs: [build-lib]
    runs-on: macos-13-xl
    env:
      api-level: 31
      target: google_apis
      arch: x86_64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: |
            lib
            node_modules
            example/node_modules
          key: temp-${{ github.sha }}

      - name: Build dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api-level }}
          target: ${{ env.target }}
          arch: ${{ env.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('example/**/*.gradle*', 'example/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Checking AVD
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api-level }}
          target: ${{ env.target }}
          arch: ${{ env.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            echo "::group::Running Android app"
            yarn android
            echo "::endgroup::"
            echo "::group::Running Gradle Build"
            cd example/android && ./gradlew connectedCheck
            echo "::endgroup::"

  run-sonar:
    name: Collect Sonar reports
    needs: [build-lib]
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ env.SONAR_TOKEN != 0 }}

      - name: Install Tools
        run: |
          brew install sonar-scanner

      - name: Restore lib
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: |
            lib
            node_modules
            example/node_modules
          key: temp-${{ github.sha }}

      - name: Run Sonar
        run: |
          git fetch --unshallow --no-tags
          sonar-scanner -Dsonar.token=${{ secrets.SONAR_TOKEN }}

  delete-chach:
    name: Clean up
    runs-on: ubuntu-latest
    needs: [run-sonar, test-Android, test-iOS]
    if: always()
    steps:
      - name: Delete temporary cache
        run: |
          curl -L \
           -X DELETE \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${{ env.GITHUB_ACTION_REPOSITORY }}/actions/caches/temp-${{ github.sha }}
