name: Collect Sonar reports
permissions:
  contents: read
  actions: write
  pull-requests: read

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  run-sonar:
    name: Collect Sonar reports
    runs-on: macos-15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Install Tools
        run: |
          brew install sonar-scanner

      - name: Download library
        uses: actions/download-artifact@v7
        with:
          name: built-lib
          path: lib

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Download Swift coverage report
        uses: actions/download-artifact@v7
        with:
          name: swift-coverage-report
          path: reports

      - name: Download Kotln coverage report
        uses: actions/download-artifact@v7
        with:
          name: kotlin-coverage-report
          path: reports

      - name: Download JS coverage report
        uses: actions/download-artifact@v7
        with:
          name: js-coverage-report
          path: reports          

      - name: Run Sonar
        run: |
          sonar-scanner -Dsonar.token=${{ secrets.SONAR_TOKEN }} -X
